// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/engine-card/AllVariants.tsx": () => import("../components/mockups/engine-card/AllVariants.tsx"),
  "./components/mockups/engine-card/ChipBlocks.tsx": () => import("../components/mockups/engine-card/ChipBlocks.tsx"),
  "./components/mockups/engine-card/CircuitChip.tsx": () => import("../components/mockups/engine-card/CircuitChip.tsx"),
  "./components/mockups/engine-card/NeuralPulse.tsx": () => import("../components/mockups/engine-card/NeuralPulse.tsx")
};
